name: Update Homebrew Tap

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Select the tag to update Homebrew'
        required: true
        type: string
  repository_dispatch:
    types: [trigger-homebrew-update]

jobs:
  update-homebrew:
    runs-on: macos-latest
    steps:
    - name: Set version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "VERSION=${{ inputs.tag }}" >> $GITHUB_ENV
        else
          echo "VERSION=${{ github.event.client_payload.version }}" >> $GITHUB_ENV
        fi

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Update Homebrew Formula
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: make update-homebrew 